src/third_party/chromite/appengine/cq_stats/build_annotations/urls.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Url disptacher for the build_annotations app."""

from __future__ import print_function

from django import http
from django.conf import urls

from build_annotations import views


urlpatterns = urls.patterns(
    '',
    urls.url(r'^$',
             lambda r: http.HttpResponseRedirect(
                 'builds_list/master-paladin/')),
    urls.url(r'^builds_list/(?P<build_config>[\w-]+)/$',
             views.ListBuildsView.as_view(),
             name='builds_list'),
    urls.url(r'edit_annotations/(?P<build_config>[\w-]+)/(?P<build_id>\d+)/$',
             views.EditAnnotationsView.as_view(),
             name='edit_annotations'))

src/third_party/chromite/appengine/cq_stats/cq_stats/urls.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""The main url dispatcher for this project."""

from __future__ import print_function

from django import http
from django.conf import urls


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
urlpatterns = urls.patterns(
    '',
    urls.url(r'^$', lambda r: http.HttpResponseRedirect('build_annotations/')),
    urls.url(r'^build_annotations/', urls.include(
        'build_annotations.urls',
        namespace='build_annotations')))

src/third_party/chromite/appengine/cq_stats/build_annotations/forms.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Forms used by the build_annotations app."""

from __future__ import print_function

from django import forms

from build_annotations import models as ba_models


class SearchForm(forms.Form):
  """Form to limit builds shown on the landing page."""
  latest_build_id = forms.IntegerField()
  num_builds = forms.IntegerField(label='Number of results')


class AnnotationsForm(forms.ModelForm):
  """Form to add/edit a single annotation to a build."""

  # pylint: disable=no-init, old-style-class
  class Meta:
    """Set meta options for the form."""
    model = ba_models.AnnotationsTable
    fields = ['failure_category', 'failure_message', 'blame_url', 'notes',
              'deleted']


# NB: Explicitly set can_delete=False for clarity.
# Due to a bug in (< django-1.7), models get deleted when the formset is saved
# even if we request not to commit changes.
AnnotationsFormSet = forms.models.modelformset_factory(
    ba_models.AnnotationsTable,
    form=AnnotationsForm,
    can_delete=False)

src/third_party/chromite/appengine/cq_stats/build_annotations/views.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""All django views for the build_annotations app."""

from __future__ import print_function

from django import http
from django import shortcuts
from django.core import urlresolvers
from django.views import generic
from google.appengine.api import users

from build_annotations import build_row_controller
from build_annotations import models as ba_models
from build_annotations import forms as ba_forms


_DEFAULT_USERNAME = "SomeoneGotHereWithoutLoggingIn"

class ListBuildsView(generic.list.ListView):
  """The landing page view of the app. Lists requested builds."""

  template_name = 'build_annotations/index.html'

  def __init__(self, *args, **kwargs):
    super(ListBuildsView, self).__init__(*args, **kwargs)
    self._username = _DEFAULT_USERNAME
    self._build_config = None
    self._search_form = None
    self._controller = None
    self._session = None
    self._builds_list = None
    self._hist = None

  def get_queryset(self):
    self._EnsureSessionInitialized()
    self._controller = build_row_controller.BuildRowController()
    build_config_q = None
    if self._build_config is not None:
      build_config_q = self._controller.GetQRestrictToBuildConfig(
          self._build_config)
    self._builds_list = self._controller.GetStructuredBuilds(
        latest_build_id=self._session['latest_build_id'],
        num_builds=self._session['num_builds'],
        extra_filter_q=build_config_q)
    self._hist = self._controller.GetHandlingTimeHistogram(
        latest_build_id=self._session['latest_build_id'],
        num_builds=self._session['num_builds'],
        extra_filter_q=build_config_q)
    return self._builds_list

  def get_context_object_name(self, _):
    return 'builds_list'

  def get_context_data(self, **kwargs):
    context = super(ListBuildsView, self).get_context_data(**kwargs)
    context['username'] = self._username
    context['search_form'] = self._GetSearchForm()
    context['latest_build_id_cached'] = self._GetLatestBuildId()
    context['build_config'] = self._build_config
    context['histogram_data'] = self._hist
    return context

  # pylint: disable=arguments-differ
  def get(self, request, build_config=None):
    # We're assured that a username exists in prod because our app sits behind
    # appengine login. Not so when running from dev_appserver.
    self._username = users.get_current_user()
    self._session = request.session
    self._build_config = build_config
    return super(ListBuildsView, self).get(request)

  def post(self, request, build_config):
    self._session = request.session
    form = ba_forms.SearchForm(request.POST)
    self._search_form = form
    if form.is_valid():
      self._session['latest_build_id'] = form.cleaned_data['latest_build_id']
      self._session['num_builds'] = form.cleaned_data['num_builds']
    return self.get(request, build_config)

  def put(self, *args, **kwargs):
    return self.post(*args, **kwargs)

  def _GetSearchForm(self):
    if self._search_form is not None:
      return self._search_form
    return ba_forms.SearchForm(
        {'latest_build_id': self._session['latest_build_id'],
         'num_builds': self._session['num_builds']})

  def _EnsureSessionInitialized(self):
    latest_build_id = self._session.get('latest_build_id', None)
    num_results = self._session.get('num_builds', None)
    if latest_build_id is None or num_results is None:
      # We don't have a valid search history in this session, obtain defaults.
      controller = build_row_controller.BuildRowController()
      controller.GetStructuredBuilds(num_builds=1)
      self._session['latest_build_id'] = controller.latest_build_id
      self._session['num_builds'] = controller.DEFAULT_NUM_BUILDS

  def _GetLatestBuildId(self):
    controller = build_row_controller.BuildRowController()
    controller.GetStructuredBuilds(num_builds=1)
    return controller.latest_build_id


class EditAnnotationsView(generic.base.View):
  """View that handles annotation editing page."""

  template_name = 'build_annotations/edit_annotations.html'

  def __init__(self, *args, **kwargs):
    self._username = _DEFAULT_USERNAME
    self._formset = None
    self._context = {}
    self._request = None
    self._session = None
    self._build_config = None
    self._build_id = None
    super(EditAnnotationsView, self).__init__(*args, **kwargs)

  def get(self, request, build_config, build_id):
    # We're assured that a username exists in prod because our app sits behind
    # appengine login. Not so when running from dev_appserver.
    self._username = users.get_current_user()
    self._request = request
    self._build_config = build_config
    self._build_id = build_id
    self._session = request.session
    self._PopulateContext()
    return shortcuts.render(request, self.template_name, self._context)

  def post(self, request, build_config, build_id):
    # We're assured that a username exists in prod because our app sits behind
    # appengine login. Not so when running from dev_appserver.
    self._username = users.get_current_user()
    self._request = request
    self._build_config = build_config
    self._build_id = build_id
    self._session = request.session
    self._formset = ba_forms.AnnotationsFormSet(request.POST)
    if self._formset.is_valid():
      self._SaveAnnotations()
      return http.HttpResponseRedirect(
          urlresolvers.reverse('build_annotations:edit_annotations',
                               args=[self._build_config, self._build_id]))
    else:
      self._PopulateContext()
      return shortcuts.render(request, self.template_name, self._context)

  def _PopulateContext(self):
    build_row = self._GetBuildRow()
    if build_row is None:
      raise http.Http404

    self._context = {}
    self._context['username'] = self._username
    self._context['build_config'] = self._build_config
    self._context['build_row'] = build_row
    self._context['annotations_formset'] = self._GetAnnotationsFormSet()

  def _GetBuildRow(self):
    controller = build_row_controller.BuildRowController()
    build_row_list = controller.GetStructuredBuilds(
        latest_build_id=self._build_id,
        num_builds=1)
    if not build_row_list:
      return None
    return build_row_list[0]

  def _GetAnnotationsFormSet(self):
    if self._formset is None:
      build_row = self._GetBuildRow()
      if build_row is not None:
        queryset = build_row.GetAnnotationsQS()
      else:
        queryset = ba_models.AnnotationsTable.objects.none()
      self._formset = ba_forms.AnnotationsFormSet(queryset=queryset)
    return self._formset

  def _SaveAnnotations(self):
    models_to_save = self._formset.save(commit=False)
    build_row = self._GetBuildRow()
    for model in models_to_save:
      if not hasattr(model, 'build_id') or model.build_id is None:
        model.build_id = build_row.build_entry
      model.last_annotator = self._username
      model.save()

src/third_party/chromite/appengine/cq_stats/build_annotations/templates/build_annotations/base.html
<html lang="en">
  <head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'build_annotations/base.css' %}"/>
  <script type="text/javascript"
          daja-dojo-config="async:true"
          src="//ajax.googleapis.com/ajax/libs/dojo/1.10.3/dojo/dojo.js"></script>
  <script type="text/javascript" src="{% static 'build_annotations/base.js' %}"></script>

  {% block template-private-imports %}
  <!-- This is especially needed for the django 'load' command which works like
       python import - loaded files are private to the template -->
  {% endblock %}
  </head>

  <body>
    {% block welcome-header %}
    <p style="text-align: right">Welcome {{ username }}! 'notate 'em all!</p>
    {% endblock %}

    {% block content %}
    <p style="color: red; layout: block">
      All the page's real content should have gone here.
      If you're reading me, someone forgot to do their homework.
    </p>
    {% endblock %}  <!-- content -->
  </body>
</html>

src/third_party/chromite/appengine/cq_stats/build_annotations/templates/build_annotations/edit_annotations.html
{% extends 'build_annotations/base.html' %}

{% block template-private-imports %}
{% load build_annotations_filters %}
{% endblock %}

{% block content %}
<h1>Annotate {{ build_config|title }} Build {{ build_row.id }}</h1>
<ul class="navbar">
  <li class="navbar">
    <a class="navbar" href="{% url 'build_annotations:builds_list' build_config %}">Builds List</a>
  </li>
</ul>

<table class="build_details">
  <tr>
    <th class="build_details">Build Number</th>
    <td class="build_details"><a class="external_link" href="https://uberchromegw.corp.google.com/i/{{ build_row.waterfall }}/builders/{{ build_row.builder_name }}/builds/{{ build_row.build_number }}" target="_blank" rel="nofollow">{{ build_row.build_number }}</a></td>
  </tr>
  <tr>
    <th class="build_details">Status</th>
    <td class="build_details">{{ build_row.status }}</td>
  </tr>
  <tr>
    <th class="build_details">Summary</th>
    <td class="build_details">{{ build_row.summary|linebreaksbr }}</td>
  </tr>
  <tr>
    <th class="build_details">Start Time</th>
    <td class="build_details" name="date.datetz">{{ build_row.start_time|date:"D, d M Y H:i" }} UTC</td>
  </tr>
  <tr>
    <th class="build_details">Runtime</th>
    <td class="build_details">{{ build_row.run_time }}</td>
  </tr>
  <tr>
    <th class="build_details">Weekday</th>
    <td class="build_details">{{ build_row.weekday }}</td>
  </tr>
  <tr>
    <th class="build_details">ChromeOS Version</th>
    <td class="build_details">{{ build_row.chromeos_version }}</td>
  </tr>
  <tr>
    <th class="build_details">Chrome Version</th>
    <td class="build_details">{{ build_row.chrome_version }}</td>
  </tr>
  <tr>
    <th class="build_details">Failed Stages</th>
    <td class="build_details">{{ build_row.failed_stages }}</td>
  </tr>
  <tr>
    <th class="build_details">CLs Picked Up</th>
    <td class="build_details">{{ build_row.picked_up_count }}</td>
  </tr>
  <tr>
    <th class="build_details">CLs Submitted</th>
    <td class="build_details">{{ build_row.submitted_count }}</td>
  </tr>
  <tr>
    <th class="build_details">CLs Kicked Out</th>
    <td class="build_details">{{ build_row.kicked_out_count }}</td>
  </tr>
</table>
<form action="{% url 'build_annotations:edit_annotations' build_config build_row.id %}"
      method="post">
  {% csrf_token %}
  {{ annotations_formset.management_form }}
  <table class="annotations_list">
    <tr>
    {% for form in annotations_formset %}
      {% if forloop.first %}
        <tr>
          <th class="annotations_list">Failure Category</th>
          <th class="annotations_list">Failure Message</th>
          <th class="annotations_list">Blame URL</th>
          <th class="annotations_list">Notes</th>
          <th class="annotations_list">Update</th>
        </tr>
      {% endif %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% if not forloop.last %}
        <tr id="annotation_{{ forloop.counter }}_noedit">
          <td>{{ form.failure_category.value|default_if_none:""|striptags|crosurlize|linebreaks }}</td>
          <td>{{ form.failure_message.value|default_if_none:""|striptags|crosurlize|linebreaks }}</td>
          <td>{{ form.blame_url.value|default_if_none:""|striptags|crosurlize|linebreaks }}</td>
          <td>{{ form.notes.value|default_if_none:""|striptags|crosurlize|linebreaks }}</td>
          <td><a href="javascript:void(0)" onclick="editAnnotation('{{ forloop.counter }}')">edit</a>
        </tr>
      {% endif %}

      {% if not forloop.last %}
        <tr id="annotation_{{ forloop.counter }}_edit" class="hidden">
      {% else %}
        <tr id="annotation_{{ forloop.counter }}_edit">
      {% endif %}
            <td class="annotations_list">{{ form.failure_category }}<br><div class="errorlist">{{ form.failure_category.errors }}</div></td>
            <td class="annotations_list">{{ form.failure_message }}<br><div class="errorlist">{{ form.failure_message.errors }}</div></td>
            <td class="annotations_list">{{ form.blame_url }}<br><div class="errorlist">{{ form.blame_url.errors }}</div></td>
            <td class="annotations_list">{{ form.notes }}<br><div class="errorlist">{{ form.notes.errors }}</div></td>
            <td class="annotations_list">Mark for deletion: {{ form.deleted }}<br><div class="errorlist">{{ form.deleted.errors }}</div></td>
        </tr>
    {% endfor %}
  </table>
  <input type="submit" value="Save Changes"/>
</form>
{% endblock %}  <!-- content -->

src/third_party/chromite/appengine/cq_stats/build_annotations/templates/build_annotations/index.html
{% extends 'build_annotations/base.html' %}

{% block template-private-imports %}
  <!-- Call this once on every web page. -->
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>

  <script type="text/javascript">
    // Load the Google Charts "core" charts (bar, line, pie...)
    google.load("visualization", '1', {packages:['corechart']});
    // When the page loads call the drawChart() function.
    google.setOnLoadCallback(drawChart);

    function drawChart() {
      var data = google.visualization.arrayToDataTable([          // The chart data.
        ['CL', 'Handling Time (minutes)'],
        {% for key, value in histogram_data.items %}
        ['{{ key }}', {{ value }}],
        {% endfor %}
      ]);

      var options = {      // Customize a few of Google Charts' hundreds of options.
        title: 'Histogram: Patch handling times',
        width: 600,
        height: 400,
        hAxis: { title: 'Patch handling time', },
        vAxis: { title: '# Patches', },
      };

      // Create and draw a Google Column Chart.
      // To experiment with different types of charts, replace "ColumnChart" with
      // the desired chart type (e.g., "PieChart", "LineChart").
      var chart = new google.visualization.Histogram(document.getElementById('chart_div'));
      google.visualization.events.addListener(chart, 'ready', function() {
        document.getElementById('chart_img_div').innerHTML = '<a href="' + chart.getImageURI() + '">Save Chart</a>'
      })
      chart.draw(data, options);
    }
  </script>

{% endblock %}  <!-- template-private-impots -->
{% block content %}
<h1> {{ build_config|title }} Builds</h1>
<ul class="navbar">
  <li class="navbar">
    <a class="navbar" href="{% url 'build_annotations:builds_list' 'master-paladin' %}">Master-Paladin</a>
  </li>
  <li class="navbar">
    <a class="navbar" href="{% url 'build_annotations:builds_list' 'master-release' %}">Master-Release</a>
  </li>
  <li class="navbar">
    <a class="navbar" href="{% url 'build_annotations:builds_list' 'master-chromium-pfq' %}">Chromium-PFQ</a>
  </li>
</ul>
<form action="{% url 'build_annotations:builds_list' build_config %}" method="post">
  {% csrf_token %}
  <table>
    <tr>
      <th><label>{{ search_form.latest_build_id.label }}</label></th>
      <td>{{ search_form.latest_build_id }}</td>
      <td>
        <button type="button" onclick="populateLatest()">Get latest</button>
        <input type="hidden" id="latest_build_id_cached" value="{{ latest_build_id_cached }}"/>
      </td>
      <td class="error_message">{{ search_form.latest_build_id.errors }}</td>
    </tr>
    <tr>
      <th><label>{{ search_form.num_builds.label }}</label></th>
      <td>{{ search_form.num_builds }}</td>
      <td class="error_message">{{ search_form.num_builds.errors }}</td>
    </tr>
  </table>
  <input type="submit" value="Update List"/>
</form>

<div id='chart_div_container' class='centered_div_container'>
  <div id='chart_div' class='centered_div_block'></div>
  <div id='chart_img_div' class='centered_div_block'></div>
</div>

<table class="build_list">
  <tr>
    <th class="build_list">Build ID</th>
    <th class="build_list">Build Number</th>
    <th class="build_list">Status</th>
    <th class="build_list">Summary</th>
    <th class="build_list">Start Time</th>
    <th class="build_list">Runtime</th>
    <th class="build_list">CLs Picked Up</th>
    <th class="build_list">Submitted</th>
    <th class="build_list">Rejected</th>
    <th class="build_list">Annotation Summary</th>
  </tr>
{% for build_row in builds_list %}
  <tr class="build_item_{{ build_row.status }}">
    <td class="build_list"><a href="{% url 'build_annotations:edit_annotations' build_config build_row.id %}">{{ build_row.id }}</a></td>
    <td class="build_list">{{ build_row.build_number }}</td>
    <td class="build_list">{{ build_row.status|truncatechars:20 }}</td>
    <td class="build_list">{{ build_row.summary|truncatechars:50|cut:'\n\r' }}</td>
    <td class="build_list" name="date.datetz">{{ build_row.start_time|date:"D, d M Y H:i" }} UTC</td>
    <td class="build_list">{{ build_row.run_time }}</td>
    <td class="build_list">{{ build_row.picked_up_count }}</td>
    <td class="build_list">{{ build_row.submitted_count }}</td>
    <td class="build_list">{{ build_row.kicked_out_count }}</td>
    <td class="build_list">{{ build_row.annotation_summary|truncatechars:150 }}</td>
  </tr>
{% endfor %}
</table>
{% endblock %}  <!-- content -->